//! SQL shared by native metadata readers and their query-plan proofs.

pub(super) const TITLE_INFO: &str = "SELECT native.record_id AS owner_id, native.value_order AS row_order, native.source_order, native.name, native.value, native.source_line AS line, native.source_column AS column FROM temp.catalog_software_requested_owners AS requested CROSS JOIN software_item_info AS native WHERE native.record_id = requested.owner_id ORDER BY native.record_id, native.value_order";

pub(super) const TITLE_SHARED_FEATURES: &str = "SELECT native.record_id AS owner_id, native.value_order AS row_order, native.source_order, native.name, native.value, native.source_line AS line, native.source_column AS column FROM temp.catalog_software_requested_owners AS requested CROSS JOIN software_item_shared_features AS native WHERE native.record_id = requested.owner_id ORDER BY native.record_id, native.value_order";

pub(super) const NEXT_LIST_PAGE: &str = "SELECT groups.set_group_id AS id, lists.namespace_id AS native_id, lists.name, lists.description, lists.notes, groups.list_order AS order_value, lists.source_order, lists.source_line AS line, lists.source_column AS column, 1 AS group_snapshot_ok, groups.kind AS group_kind FROM catalog_set_groups AS groups LEFT JOIN software_lists AS lists ON lists.namespace_id = groups.set_group_id WHERE groups.snapshot_key = ? AND groups.kind = 'software_list' AND (groups.list_order, groups.set_group_id) > (?, ?) ORDER BY groups.list_order, groups.set_group_id LIMIT ?";

pub(super) const FIRST_LIST_PAGE: &str = "SELECT groups.set_group_id AS id, lists.namespace_id AS native_id, lists.name, lists.description, lists.notes, groups.list_order AS order_value, lists.source_order, lists.source_line AS line, lists.source_column AS column, 1 AS group_snapshot_ok, groups.kind AS group_kind FROM catalog_set_groups AS groups LEFT JOIN software_lists AS lists ON lists.namespace_id = groups.set_group_id WHERE groups.snapshot_key = ? AND groups.kind = 'software_list' ORDER BY groups.list_order, groups.set_group_id LIMIT ?";

pub(super) const NEXT_TITLE_PAGE: &str = "SELECT sets.set_id AS id, sets.set_name AS name, sets.list_order AS order_value, items.record_id AS native_id, items.source_order, sets.source_line AS line, sets.source_column AS column, items.clone_of, items.supported, items.supported_specified, items.description, items.year, items.publisher, items.notes FROM catalog_sets AS sets LEFT JOIN software_items AS items ON items.record_id = sets.set_id JOIN catalog_set_groups AS groups ON groups.set_group_id = sets.set_group_id WHERE groups.snapshot_key = ? AND groups.kind = 'software_list' AND groups.set_group_id = ? AND sets.source_element_kind = 'software_item' AND (sets.list_order, sets.set_id) > (?, ?) ORDER BY sets.list_order, sets.set_id LIMIT ?";

pub(super) const FIRST_TITLE_PAGE: &str = "SELECT sets.set_id AS id, sets.set_name AS name, sets.list_order AS order_value, items.record_id AS native_id, items.source_order, sets.source_line AS line, sets.source_column AS column, items.clone_of, items.supported, items.supported_specified, items.description, items.year, items.publisher, items.notes FROM catalog_sets AS sets LEFT JOIN software_items AS items ON items.record_id = sets.set_id JOIN catalog_set_groups AS groups ON groups.set_group_id = sets.set_group_id WHERE groups.snapshot_key = ? AND groups.kind = 'software_list' AND groups.set_group_id = ? AND sets.source_element_kind = 'software_item' ORDER BY sets.list_order, sets.set_id LIMIT ?";

pub(super) const PUBLISHED_SNAPSHOT: &str = "SELECT registry.registry_uuid, snapshots.snapshot_key, sources.source_key, sources.display_name AS source_name, catalogs.catalog_key, catalogs.display_name AS catalog_name, documents.document_key, snapshots.interpretation_key, interpretations.format, software.envelope_kind, headers.build, CASE WHEN headers.snapshot_key IS NULL THEN 0 ELSE 1 END AS wrapper_header_count FROM catalog_snapshots AS snapshots JOIN snapshot_publications AS publication ON publication.snapshot_key = snapshots.snapshot_key AND publication.catalog_key = snapshots.catalog_key AND publication.document_key = snapshots.document_key AND publication.interpretation_key = snapshots.interpretation_key JOIN catalogs ON catalogs.catalog_key = snapshots.catalog_key JOIN publishing_sources AS sources ON sources.source_key = catalogs.source_key JOIN documents ON documents.document_key = snapshots.document_key JOIN parser_interpretations AS interpretations ON interpretations.interpretation_key = snapshots.interpretation_key JOIN software_documents AS software ON software.snapshot_key = snapshots.snapshot_key CROSS JOIN file_id_registries AS registry LEFT JOIN software_wrapper_headers AS headers ON headers.snapshot_key = software.snapshot_key WHERE snapshots.snapshot_key = ? AND registry.registry_id = 1 AND interpretations.format = 'mame-softwarelist-xml'";

pub(super) const SELECTED_LIST: &str = "SELECT groups.set_group_id AS id, lists.namespace_id AS native_id, lists.name, lists.description, lists.notes, groups.list_order AS order_value, lists.source_order, lists.source_line AS line, lists.source_column AS column, groups.snapshot_key = ? AS group_snapshot_ok, groups.kind AS group_kind FROM catalog_set_groups AS groups LEFT JOIN software_lists AS lists ON lists.namespace_id = groups.set_group_id WHERE groups.set_group_id = ?";

pub(super) const LIST_TEXT_POSITIONS: &str = "SELECT positions.namespace_id AS owner_id, positions.field_kind, positions.source_order, positions.source_line AS line, positions.source_column AS column FROM temp.catalog_software_requested_owners AS requested CROSS JOIN software_list_text_positions AS positions WHERE positions.namespace_id = requested.owner_id ORDER BY positions.namespace_id, positions.source_order";

pub(super) const TITLE_TEXT_POSITIONS: &str = "SELECT positions.record_id AS owner_id, positions.field_kind, positions.source_order, positions.source_line AS line, positions.source_column AS column FROM temp.catalog_software_requested_owners AS requested CROSS JOIN software_item_text_positions AS positions WHERE positions.record_id = requested.owner_id ORDER BY positions.record_id, positions.source_order";

pub(super) const PARTS: &str = "SELECT parts.part_id AS id, parts.record_id, parts.part_name AS name, parts.part_order AS order_value, parts.source_order, parts.interface, parts.source_line AS line, parts.source_column AS column FROM temp.catalog_software_requested_owners AS requested CROSS JOIN software_parts AS parts WHERE parts.record_id = requested.owner_id ORDER BY parts.record_id, parts.part_order";

pub(super) const PART_FEATURES: &str = "SELECT features.part_id, features.value_order AS row_order, features.source_order, features.name, features.value, features.source_line AS line, features.source_column AS column FROM temp.catalog_software_requested_owners AS requested CROSS JOIN software_parts AS parts JOIN software_part_features AS features ON features.part_id = parts.part_id WHERE parts.record_id = requested.owner_id ORDER BY features.part_id, features.value_order";

pub(super) const DIP_SWITCHES: &str = "SELECT switches.part_id, switches.dipswitch_order AS row_order, switches.source_order, switches.name, switches.tag, switches.mask, switches.source_line AS line, switches.source_column AS column FROM temp.catalog_software_requested_owners AS requested CROSS JOIN software_parts AS parts JOIN software_part_dipswitches AS switches ON switches.part_id = parts.part_id WHERE parts.record_id = requested.owner_id ORDER BY switches.part_id, switches.dipswitch_order";

pub(super) const DIP_VALUES: &str = "SELECT native.part_id, native.dipswitch_order AS switch_order, native.value_order AS row_order, native.source_order, native.name, native.value, native.is_default, native.default_specified, native.source_line AS line, native.source_column AS column FROM temp.catalog_software_requested_owners AS requested CROSS JOIN software_parts AS parts CROSS JOIN software_part_dip_values AS native WHERE parts.record_id = requested.owner_id AND native.part_id = parts.part_id ORDER BY native.part_id, native.dipswitch_order, native.value_order";

pub(super) const AREAS: &str = "SELECT areas.area_id AS id, areas.part_id, areas.record_id, data_area.area_id AS data_id, disk_area.area_id AS disk_id, COALESCE(data_area.area_name, disk_area.area_name) AS name, areas.area_kind AS kind, areas.area_order AS order_value, COALESCE(data_area.source_order, disk_area.source_order) AS source_order, data_area.declared_size_text AS size_text, data_area.declared_size AS size, data_area.width, data_area.width_specified, data_area.endianness, data_area.endianness_specified, COALESCE(data_area.source_line, disk_area.source_line) AS line, COALESCE(data_area.source_column, disk_area.source_column) AS column, parts.record_id AS part_record_id, requested.owner_id AS item_owner_id FROM temp.catalog_software_requested_owners AS requested CROSS JOIN software_parts AS parts CROSS JOIN software_areas AS areas LEFT JOIN software_data_areas AS data_area ON data_area.area_id = areas.area_id LEFT JOIN software_disk_areas AS disk_area ON disk_area.area_id = areas.area_id WHERE parts.record_id = requested.owner_id AND areas.part_id = parts.part_id ORDER BY areas.part_id, areas.area_order";

pub(super) const ROM_ENTRIES: &str = "SELECT rom.area_id, rom.occurrence_id, rom.record_id, occurrence.record_id AS occurrence_record_id, occurrence.claim_kind, rom.component_order, rom.source_order, area.record_id AS area_record_id, area.area_kind FROM temp.catalog_software_requested_owners AS requested CROSS JOIN software_areas AS area CROSS JOIN software_rom_entries AS rom LEFT JOIN asset_occurrences AS occurrence ON occurrence.occurrence_id = rom.occurrence_id WHERE requested.owner_id = area.area_id AND rom.area_id = area.area_id ORDER BY rom.area_id, rom.source_order";

pub(super) const DISK_ENTRIES: &str = "SELECT disk.area_id, disk.occurrence_id, disk.record_id, occurrence.record_id AS occurrence_record_id, occurrence.claim_kind, disk.component_order, disk.source_order, area.record_id AS area_record_id, area.area_kind FROM temp.catalog_software_requested_owners AS requested CROSS JOIN software_areas AS area CROSS JOIN software_disk_entries AS disk LEFT JOIN asset_occurrences AS occurrence ON occurrence.occurrence_id = disk.occurrence_id WHERE requested.owner_id = area.area_id AND disk.area_id = area.area_id ORDER BY disk.area_id, disk.source_order";
