[package]
name = "mame_coalesce"
version = "0.1.0"
authors = ["Michael J. Cohen <mjc@kernel.org>"]
edition = "2018"

[profile.release]
debug = true

[dependencies]
log = "0.4"
hex = { version = "0.4", features = ["serde"] }
pretty_env_logger = "0.4"
indicatif = "0.16"
rayon = "1.1"
serde_derive = "1.0.98"
serde = "1.0.98"
serde-xml-rs = "0.5"

zip = "0.5"
compress-tools = "0.12"

crc32fast = "1.3"
sha-1 = { version = "0.10", features = ["asm"] }
memmap2 = "0.5"

structopt = { version = "0.3", default-features = false }

walkdir = "^2.2.9"
tempdir = "0.3"

diesel = { version = "*", features = ["sqlite"] }
diesel_migrations = "1.4"
diesel_logger = "0.1.1"
dotenv = "0.15.0"
tree_magic = "0.2"                                # bindet?
