[package]
name = "mame_coalesce"
version = "0.1.0"
authors = ["Michael J. Cohen <mjc@kernel.org>"]
edition = "2018"

[profile.release]
debug = true
# panic = "abort"
# lto takes forever
# lto = true
# might as well turn this off too for now
# codegen-units = 1

[profile.performance]
inherits = "release"
opt-level = "s"
debug = false
panic = "abort"
lto = true
codegen-units = 1


[dependencies]
log = "0.4"
simplelog = "0.11"
indicatif = "0.16"

rayon = "1.1"

serde_derive = "1.0.98"
serde = "1.0.98"
serde-xml-rs = "0.5"

zip = { version = "0.5", features = ["deflate", "bzip2"] }

compress-tools = "0.12"

hex = { version = "0.4", features = ["serde"] }
crc32fast = "1.3"
sha-1 = { version = "0.10", features = ["asm"] }

memmap2 = "0.5"

clap = { version = "3.0", features = ["derive", "env", "suggestions"] }

camino = { version = "1.0", features = ["serde1"] }
walkdir = "^2.2.9"

diesel = { version = "*", features = ["sqlite", "r2d2", "chrono"] }
r2d2 = "0.8"
diesel_migrations = "1.4"
diesel_logger = "0.1.1"
chrono = "0.4"


infer = { version = "0.6" }

[dependencies.flate2]
version = "1.0"
default-features = false
features = ["cloudflare_zlib"]
