[package]
name = "mame_coalesce"
version = "0.1.0"
authors = ["Michael J. Cohen <mcohen@weedmaps.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
hex = {version = "0.4", features = ["serde"]}
pretty_env_logger = "0.4"
indicatif = "0.16"
rayon =  "1.1"
serde_derive = "1.0.98"
serde = "1.0.98"
serde-xml-rs = "0.5"

zip = "0.5"

crc32fast = "1.3"
sha-1 = "0.10"
md-5 = "0.10"
memmap2 = "0.5"

structopt = { version = "0.3", default-features = false }
walkdir = "^2.2.9"

diesel = { version = "*", features = ["sqlite"] }
diesel_migrations = "1.4"
diesel_logger = "0.1.1"
dotenv = "0.15.0"
tree_magic = "0.2" # bindet?