[package]
name = "mame_coalesce"
version = "0.1.0"
authors = ["Michael J. Cohen <mcohen@weedmaps.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = "0.16"
rayon =  "1.1"
serde_derive = "1.0.98"
serde = "1.0.98"
serde-xml-rs = "0.5"
sha-1 = "0.10"
structopt = { version = "0.3", default-features = false }
walkdir = "^2.2.9"
zip = "^0.5.2"
async-std = { version = "1.10", features = ["attributes"] }

[dependencies.sqlx]
version = "0.5"
features = [ "sqlite", "migrate", "time", "runtime-async-std-rustls" ]


[dependencies.sea-orm]
version = "0.4"
features = [ "sqlx-sqlite", "runtime-async-std-rustls", "macros" ]
default-features = false