[package]
name = "mame_coalesce"
version = "0.1.0"
authors = ["Michael J. Cohen <mcohen@weedmaps.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
