[package]
name = "mame_coalesce"
version = "0.1.0"
authors = ["Michael J. Cohen <mjc@kernel.org>"]
edition = "2021"

[profile.release]
debug = true
lto = "thin"

[profile.performance]
inherits = "release"
opt-level = "s"
debug = false
panic = "abort"
lto = true
codegen-units = 1


[dependencies]
log = "0.4"
simplelog = "0.11"
indicatif = { version = "0.16", features = ["rayon"] }

rayon = "1.1"

serde_derive = "1.0.98"
serde = "1.0.98"
serde-xml-rs = "0.5"

zip = { version = "0.6", features = ["deflate", "bzip2", "zstd"] }

compress-tools = "0.12"

hex = { version = "0.4", features = ["serde"] }
sha-1 = { version = "0.10", features = ["asm"] }
xxhash-rust = { version = "0.8", features = ["xxh3"] }

memmap2 = "0.5"
fmmap = "0.2"

clap = { version = "3.0.14", features = ["derive", "env", "suggestions"] }

camino = { version = "1.0", features = ["serde1"] }
walkdir = "^2.2.9"

diesel = { version = "1.4", features = ["sqlite", "r2d2", "chrono"] }
r2d2 = "0.8"
diesel_migrations = "1.4"
diesel_logger = "0.1.1"
chrono = "0.4"


infer = { version = "0.7" }

# I don't know why but 1.1.5 segfaults if you don't include this, instead of letting flate2 pull it in.
libz-sys = {version = "1.1", features = ["zlib-ng"]}

[dependencies.flate2]
version = "1.0"
default-features = false
features = ["zlib-ng-compat"]
