[package]
name = "mame_coalesce"
version = "0.1.0"
authors = ["Michael J. Cohen <mcohen@weedmaps.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon =  "^1.1"
serde_derive = "^1.0.98"
serde = "^1.0.98"
serde-xml-rs = "^0.3.1"
sha-1 = "^0.8.1"
walkdir = "^2.2.9"
