#!/usr/bin/env python3
"""Constructed native numeric witnesses; no application database or source IO."""

import sqlite3
import unittest

import assemble
import count_fixtures
from software_count_mapping_check import EXPECTED_COUNTS


# Literal expected interpretations, not generated by the SQL being checked.
VALUES = (
    (None, None), ('', None), ('0', 0), ('000', 0), ('8', 8),
    ('010', 8), ('01010', 520), ('08', None), ('0009', None),
    ('0x10', 16), ('0Xabcdef', 11259375), ('0x', None), ('0xg', None),
    ('9223372036854775807', 9223372036854775807),
    ('9223372036854775808', None), ('18446744073709551615', None),
    ('0x7fffffffffffffff', 9223372036854775807),
    ('0X8000000000000000', None), ('0xffffffffffffffff', None),
    ('+1', None), ('-0', None), ('0x+1', None), ('0x-0', None),
    (' 1', None), ('1 ', None), ('1\n', None), ('1.0', None),
    ('1e2', None), ('1suffix', None), ('1\x00tail', None),
    ('\x001', None), ('１２', None), ('١٢', None),
    ('0' * 4096, 0), ('0x' + '0' * 4096 + '1', 1),
)


class SoftwareNumbers(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.db = sqlite3.connect(':memory:')
        cls.addClassCleanup(cls.db.close)
        cls.db.execute('PRAGMA foreign_keys=ON')
        cls.db.executescript(assemble.assemble())
        cls.db.executescript((assemble.ROOT / 'software_field_witnesses.sql').read_text())
        count_fixtures.seal(cls.db, 'software', 1, EXPECTED_COUNTS)
        problems = cls.db.execute('SELECT * FROM candidate_integrity_problems').fetchall()
        if problems:
            raise AssertionError(f'constructed native baseline is not clean: {problems}')
        cls.db.commit()

    def setUp(self):
        self.db.execute('SAVEPOINT numeric_case')
        self.addCleanup(self.db.execute, 'RELEASE numeric_case')
        self.addCleanup(self.db.execute, 'ROLLBACK TO numeric_case')

    def test_rom_size_and_offset_use_the_same_native_grammar(self):
        for text, expected in VALUES:
            with self.subTest(text=repr(text)[:80]):
                self.db.execute(
                    'UPDATE software_rom_load_entries SET size_text=?,offset_text=? '
                    'WHERE media_entry_id=400', (text, text),
                )
                self.assertEqual(self.db.execute(
                    'SELECT byte_length,byte_offset FROM candidate_software_rom_numbers '
                    'WHERE media_entry_id=400'
                ).fetchone(), (expected, expected))
                self.assertEqual(self.db.execute(
                    'SELECT size_text,offset_text FROM software_rom_load_entries '
                    'WHERE media_entry_id=400'
                ).fetchone(), (text, text))

    def test_data_area_size_uses_the_same_grammar_without_rejecting_retained_text(self):
        for text, expected in VALUES:
            if text is None:  # Required native attribute; omission is not a numeric state.
                continue
            with self.subTest(text=repr(text)[:80]):
                self.db.execute(
                    'UPDATE software_data_areas SET declared_size_text=? WHERE area_id=300',
                    (text,),
                )
                self.assertEqual(self.db.execute(
                    'SELECT byte_length FROM candidate_software_data_area_numbers '
                    'WHERE area_id=300'
                ).fetchone(), (expected,))

    def test_query_views_do_not_add_persisted_numeric_columns(self):
        for table, view, key in (
            ('software_rom_load_entries', 'candidate_software_rom_numbers', 'media_entry_id'),
            ('software_data_areas', 'candidate_software_data_area_numbers', 'area_id'),
        ):
            with self.subTest(table=table):
                self.assertEqual(self.db.execute(
                    'SELECT type FROM sqlite_schema WHERE name=?', (view,)
                ).fetchone(), ('view',))
                columns = {row[1] for row in self.db.execute(f'PRAGMA table_xinfo({table})')}
                self.assertNotIn('byte_length', columns)
                self.assertNotIn('byte_offset', columns)
                self.assertEqual(self.db.execute(f'SELECT count(*) FROM {view}').fetchone(),
                                 self.db.execute(f'SELECT count(*) FROM {table}').fetchone())

    def test_native_point_lookups_seek_the_owner_not_scan_the_format(self):
        for view, key, value in (
            ('candidate_software_rom_numbers', 'media_entry_id', 400),
            ('candidate_software_data_area_numbers', 'area_id', 300),
        ):
            with self.subTest(view=view):
                plans = [row[3] for row in self.db.execute(
                    f'EXPLAIN QUERY PLAN SELECT byte_length FROM {view} WHERE {key}=?',
                    (value,),
                )]
                self.assertTrue(any('SEARCH' in plan and 'INTEGER PRIMARY KEY' in plan
                                    for plan in plans), plans)
                self.assertFalse(any('SCAN' in plan and ('software_rom_load_entries' in plan
                                                         or 'software_data_areas' in plan)
                                     for plan in plans), plans)

    def test_unrelated_declarations_do_not_add_point_query_work(self):
        query = ('SELECT byte_length,byte_offset FROM candidate_software_rom_numbers '
                 'WHERE media_entry_id=402')

        def instructions():
            count = 0

            def tick():
                nonlocal count
                count += 1
                return 0

            self.db.set_progress_handler(tick, 1)
            try:
                self.assertEqual(self.db.execute(query).fetchone(), (8, 15))
            finally:
                self.db.set_progress_handler(None, 0)
            return count

        instructions()  # Separate statement initialization from the comparison.
        before = instructions()
        # Real native owners, deliberately still a draft with no new count seal
        # or load-step projections. These rows must not enter this point read.
        for offset in range(512):
            identity = 10000 + offset
            self.db.execute('INSERT INTO catalog_source_elements VALUES (?,1,?)',
                            (identity, 'software_rom_entry'))
            self.db.execute('INSERT INTO catalog_media_entries VALUES (?,NULL)', (identity,))
            self.db.execute(
                'INSERT INTO software_rom_load_entries '
                '(media_entry_id,data_area_id,size_text,offset_text,status,status_specified,'
                'source_order,source_line,source_column) '
                "VALUES (?,300,'0xabcdef','010','good',0,?,1,1)",
                (identity, 10000 + offset),
            )
        after = instructions()
        self.assertLessEqual(after, before, (before, after))


if __name__ == '__main__':
    unittest.main()
