#!/usr/bin/env python3
"""Materialize the approved catalog SQL; Rust builds need no Python runtime.

The reviewed fragments and closed manifests remain the canonical input. The
checked-in SQL is a generated build artifact, not a second handwritten model.
"""

import argparse
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "docs" / "schema-candidate"))
import assemble  # noqa: E402


def generated_sql():
    return (
        "-- Generated by scripts/generate_catalog_schema.py; do not edit.\n"
        "-- Canonical approved catalog fragments: docs/schema-candidate/.\n"
        + assemble.assemble()
        + "\n"
    )


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="update the generated SQL")
    args = parser.parse_args()
    path = ROOT / "src" / "storage" / "db" / "catalog.sql"
    expected = generated_sql()
    if args.write:
        path.write_text(expected, encoding="utf-8")
        print(f"Generated {path.relative_to(ROOT)} ({len(expected.encode('utf-8')):,} bytes)")
    elif not path.exists() or path.read_text(encoding="utf-8") != expected:
        parser.exit(1, "catalog.sql is stale; run python3 scripts/generate_catalog_schema.py --write\n")
    else:
        print("Bundled catalog SQL matches the canonical approved fragments")


if __name__ == "__main__":
    main()
