include!("mame_guards.rs");

/// Complete bundled schema for direct creation, never an upgrade script.
pub const SCHEMA: &str = concat!(
    include_str!("coverage.sql"),
    "\n",
    include_str!("schema.sql"),
    "\n",
    include_str!("mame_relationships.sql"),
    "\n",
    include_str!("mame_relationship_projections.sql"),
    "\nCREATE VIEW mame_machine_dependency_rows AS WITH requested_mame_machines(set_id) AS (SELECT set_id FROM mame_machines) ",
    include_str!("mame_dependencies.sql"),
    ";\n",
    "\n",
    include_str!("mame_compatibility.sql"),
    "\n",
    include_str!("logiqx.sql"),
    "\n",
    include_str!("cmp.sql"),
    "\n",
    include_str!("catalog_registry.sql"),
    "\n",
    include_str!("file_match_reviews.sql"),
    "\n",
    include_str!("no_intro_dat.sql"),
    "\n",
    include_str!("no_intro_dat_guards.sql"),
    "\n",
    include_str!("no_intro_database.sql"),
    "\n",
    include_str!("no_intro_database_guards.sql"),
    "\n",
    include_str!("software_guards.sql"),
    "\n",
    "CREATE VIEW mame_machine_child_positions AS WITH requested_mame_machines(set_id) AS (SELECT set_id FROM mame_machines) ",
    include_str!("mame_positions.sql"),
    ";",
    "\nCREATE VIEW mame_machine_spec_elements AS WITH requested_mame_specification_owners(set_id) AS (SELECT set_id FROM mame_machines), ",
    include_str!("mame_specification.sql"),
    ";\n",
    "\n",
    mame_guards!(),
    "\nCREATE TRIGGER mame_native_publication_guard BEFORE INSERT ON snapshot_publications ",
    "WHEN EXISTS (WITH requested(snapshot_key) AS (VALUES (NEW.snapshot_key)), ",
    mame_publication_readiness!(),
    ") BEGIN SELECT RAISE(ABORT,'native MAME publication requires complete facts and unique source positions'); END;\n",
    "\nCREATE TRIGGER relationship_support_requires_published_target BEFORE INSERT ON relationship_assertion_support ",
    "WHEN EXISTS (WITH requested(assertion_key) AS (VALUES (NEW.supported_assertion_key)) SELECT 1 FROM (",
    include_str!("relationship_readiness.sql"),
    ") WHERE NOT is_published) BEGIN SELECT RAISE(ABORT,'support requires published relationship evidence'); END;\n",
    "CREATE TRIGGER relationship_reviews_require_published_evidence BEFORE INSERT ON relationship_reviews ",
    "WHEN EXISTS (WITH requested(assertion_key) AS (VALUES (NEW.assertion_key),(NEW.superseded_by_assertion_key)) SELECT 1 FROM (",
    include_str!("relationship_readiness.sql"),
    ") WHERE NOT is_published) BEGIN SELECT RAISE(ABORT,'review requires published relationship evidence'); END;\n"
);
