include!("mame_guards.rs");

/// Complete bundled schema for direct creation, never an upgrade script.
pub const SCHEMA: &str = concat!(
    include_str!("coverage.sql"),
    "\n",
    include_str!("schema.sql"),
    "\n",
    include_str!("reported_relationships.sql"),
    "\n",
    include_str!("mame_relationships.sql"),
    "\n",
    include_str!("mame_merge_guards.sql"),
    "\n",
    include_str!("mame_relationship_projections.sql"),
    "\nCREATE VIEW mame_machine_dependency_rows AS WITH requested_mame_machines(set_id) AS (SELECT set_id FROM mame_machines) ",
    include_str!("mame_dependencies.sql"),
    ";\n",
    "\n",
    include_str!("mame_compatibility.sql"),
    "\n",
    include_str!("mame_attribute_positions.sql"),
    "\n",
    include_str!("logiqx.sql"),
    "\n",
    include_str!("logiqx_attribute_positions.sql"),
    "\n",
    include_str!("cmp.sql"),
    "\n",
    include_str!("reported_relationship_guards.sql"),
    "\n",
    include_str!("logiqx_cmp_relationship_projections.sql"),
    "\n",
    include_str!("catalog_registry.sql"),
    "\n",
    include_str!("file_match_reviews.sql"),
    "\n",
    include_str!("no_intro_dat.sql"),
    "\n",
    include_str!("no_intro_dat_guards.sql"),
    "\n",
    include_str!("no_intro_database.sql"),
    "\n",
    include_str!("no_intro_database_guards.sql"),
    "\n",
    include_str!("no_intro_pc.sql"),
    "\n",
    include_str!("relationship_targets.sql"),
    "\n",
    include_str!("relationship_evidence.sql"),
    "\nCREATE VIEW catalog_relationship_closure AS WITH requested(assertion_key) AS (SELECT assertion_key FROM catalog_relationships) ",
    include_str!("relationship_readiness.sql"),
    ";\n",
    "\n",
    include_str!("relationship_reviews.sql"),
    "\nCREATE VIEW catalog_relationship_review_closure AS WITH requested_reviews(review_id) AS (SELECT review_id FROM catalog_relationship_reviews), ",
    include_str!("relationship_review_readiness_scope.sql"),
    include_str!("relationship_readiness.sql"),
    "),\n",
    include_str!("relationship_review_readiness.sql"),
    ";\n",
    "\n",
    include_str!("software_guards.sql"),
    "\n",
    include_str!("software_attribute_positions.sql"),
    "\n",
    "CREATE VIEW mame_machine_child_positions AS WITH requested_mame_machines(set_id) AS (SELECT set_id FROM mame_machines) ",
    include_str!("mame_positions.sql"),
    ";",
    "\nCREATE VIEW mame_machine_spec_elements AS WITH requested_mame_specification_owners(set_id) AS (SELECT set_id FROM mame_machines), ",
    include_str!("mame_specification.sql"),
    ";\n",
    "\n",
    mame_guards!(),
    mame_attribute_position_guards!(),
    "\nCREATE TRIGGER mame_native_publication_guard BEFORE INSERT ON snapshot_publications ",
    "WHEN EXISTS (WITH requested(snapshot_key) AS (VALUES (NEW.snapshot_key)), ",
    mame_publication_readiness!(),
    ") OR EXISTS (WITH requested(snapshot_key) AS (SELECT snapshot_key FROM mame_document_facts WHERE snapshot_key=NEW.snapshot_key), ",
    include_str!("mame_attribute_readiness.sql"),
    ") ",
    "BEGIN SELECT RAISE(ABORT,'native MAME publication requires complete facts and unique source positions'); END;\n",
    "CREATE TRIGGER catalog_relationship_reviews_insert_guard BEFORE INSERT ON catalog_relationship_reviews ",
    "WHEN typeof(NEW.review_key)<>'text' OR typeof(NEW.note)<>'text' ",
    "OR EXISTS (SELECT 1 FROM catalog_relationship_reviews WHERE review_id=NEW.review_id OR review_key=NEW.review_key) ",
    "OR length(CAST(trim(NEW.review_key,(SELECT characters FROM relationship_unicode_whitespace)) AS BLOB))=0 ",
    "OR length(CAST(trim(NEW.note,(SELECT characters FROM relationship_unicode_whitespace)) AS BLOB))=0 ",
    "OR NOT EXISTS (WITH requested(assertion_key) AS (SELECT assertion_key FROM catalog_relationships WHERE relationship_id=NEW.relationship_id) ",
    "SELECT 1 FROM (",
    include_str!("relationship_readiness.sql"),
    ") WHERE is_complete AND is_published) ",
    "BEGIN SELECT RAISE(ABORT,'relationship review references an unknown or unpublished assertion'); END;\n",
    "CREATE TRIGGER replaced_catalog_relationships_insert_guard BEFORE INSERT ON replaced_catalog_relationships ",
    "WHEN EXISTS (SELECT 1 FROM replaced_catalog_relationships WHERE review_id=NEW.review_id) ",
    "OR NOT EXISTS (SELECT 1 FROM catalog_relationship_reviews AS review WHERE review.review_id=NEW.review_id ",
    "AND review.decision='superseded' AND review.relationship_id<>NEW.replacement_relationship_id ",
    "AND NOT EXISTS (SELECT 1 FROM catalog_relationship_review_publications AS seal WHERE seal.review_id=review.review_id)) ",
    "OR NOT EXISTS (WITH requested(assertion_key) AS (SELECT assertion_key FROM catalog_relationships WHERE relationship_id=NEW.replacement_relationship_id) ",
    "SELECT 1 FROM (",
    include_str!("relationship_readiness.sql"),
    ") WHERE is_complete AND is_published) ",
    "BEGIN SELECT RAISE(ABORT,'relationship review references an unknown or unpublished assertion'); END;\n",
    "\nCREATE TRIGGER relationship_support_requires_published_target BEFORE INSERT ON catalog_relationship_evidence ",
    "WHEN EXISTS (SELECT 1 FROM catalog_relationship_evidence_publications WHERE relationship_id=NEW.relationship_id) ",
    "OR NOT EXISTS (WITH requested(assertion_key) AS (SELECT assertion_key FROM catalog_relationships WHERE relationship_id=NEW.supporting_relationship_id) ",
    "SELECT 1 FROM (",
    include_str!("relationship_readiness.sql"),
    ") WHERE is_published) ",
    "BEGIN SELECT RAISE(ABORT,'support requires published relationship evidence'); END;\n",
    "CREATE TRIGGER relationship_evidence_publications_validate BEFORE INSERT ON catalog_relationship_evidence_publications ",
    "WHEN EXISTS (SELECT 1 FROM catalog_relationship_evidence_publications WHERE relationship_id=NEW.relationship_id) ",
    "OR NOT EXISTS (WITH requested(assertion_key) AS (SELECT assertion_key FROM catalog_relationships WHERE relationship_id=NEW.relationship_id) ",
    "SELECT 1 FROM (",
    include_str!("relationship_readiness.sql"),
    ") WHERE is_complete AND owners_published) ",
    "OR ((NEW.evidence_kind='rationale') <> EXISTS (SELECT 1 FROM catalog_relationship_rationales WHERE relationship_id=NEW.relationship_id)) ",
    "OR ((NEW.evidence_kind='catalog_comparison') <> EXISTS (SELECT 1 FROM catalog_relationship_comparisons WHERE relationship_id=NEW.relationship_id)) ",
    "OR EXISTS (SELECT 1 FROM catalog_relationship_comparison_fields WHERE relationship_id=NEW.relationship_id GROUP BY disposition ",
    "HAVING MIN(list_order)<>0 OR MAX(list_order)<>COUNT(*)-1) ",
    "OR EXISTS (SELECT COUNT(*) FROM catalog_relationship_evidence WHERE relationship_id=NEW.relationship_id ",
    "HAVING MIN(list_order)<>0 OR MAX(list_order)<>COUNT(*)-1) ",
    "BEGIN SELECT RAISE(ABORT,'relationship evidence is incomplete or has an unpublished owner'); END;\n",
    "CREATE TRIGGER catalog_relationship_review_publications_validate BEFORE INSERT ON catalog_relationship_review_publications ",
    "WHEN EXISTS (SELECT 1 FROM catalog_relationship_review_publications WHERE review_id=NEW.review_id) ",
    "OR NOT EXISTS (WITH requested_reviews(review_id) AS (VALUES (NEW.review_id)), ",
    include_str!("relationship_review_readiness_scope.sql"),
    include_str!("relationship_readiness.sql"),
    "), ",
    include_str!("relationship_review_readiness.sql"),
    "WHERE request.review_id=NEW.review_id AND is_complete) ",
    "BEGIN SELECT RAISE(ABORT,'relationship review references an unknown or unpublished assertion'); END;\n",
    "CREATE TRIGGER catalog_relationship_review_publications_cycle_guard BEFORE INSERT ON catalog_relationship_review_publications ",
    "WHEN EXISTS (WITH RECURSIVE requested_reviews(review_id) AS (VALUES (NEW.review_id)), ",
    include_str!("relationship_review_active_edges.sql"),
    "SELECT 1 FROM cycle_results AS cycle JOIN catalog_relationship_reviews AS review USING(review_id) ",
    "WHERE cycle.creates_cycle AND NOT EXISTS (SELECT 1 FROM catalog_relationship_reviews AS newer ",
    "JOIN catalog_relationship_review_publications AS seal ON seal.review_id=newer.review_id ",
    "WHERE newer.relationship_id=review.relationship_id AND newer.review_id>review.review_id)) ",
    "BEGIN SELECT RAISE(ABORT,'published relationship review would create a replacement cycle'); END;\n"
);
