/// Complete bundled schema for direct creation, never an upgrade script.
pub const SCHEMA: &str = concat!(
    include_str!("coverage.sql"),
    "\n",
    include_str!("schema.sql"),
    "\n",
    include_str!("logiqx.sql"),
    "\n",
    include_str!("cmp.sql"),
    "\n",
    include_str!("catalog_registry.sql"),
    "\n",
    include_str!("file_match_reviews.sql"),
    "\n",
    include_str!("no_intro_dat.sql"),
    "\n",
    include_str!("no_intro_dat_guards.sql"),
    "\n",
    include_str!("no_intro_database.sql"),
    "\n",
    include_str!("no_intro_database_guards.sql"),
    "\n",
    include_str!("software_guards.sql"),
    "\nCREATE TRIGGER relationship_support_requires_published_target BEFORE INSERT ON relationship_assertion_support ",
    "WHEN EXISTS (WITH requested(assertion_key) AS (VALUES (NEW.supported_assertion_key)) SELECT 1 FROM (",
    include_str!("relationship_readiness.sql"),
    ") WHERE NOT is_published) BEGIN SELECT RAISE(ABORT,'support requires published relationship evidence'); END;\n",
    "CREATE TRIGGER relationship_reviews_require_published_evidence BEFORE INSERT ON relationship_reviews ",
    "WHEN EXISTS (WITH requested(assertion_key) AS (VALUES (NEW.assertion_key),(NEW.superseded_by_assertion_key)) SELECT 1 FROM (",
    include_str!("relationship_readiness.sql"),
    ") WHERE NOT is_published) BEGIN SELECT RAISE(ABORT,'review requires published relationship evidence'); END;\n"
);
