extern crate indicatif;
extern crate rayon;
#[macro_use]
extern crate serde_derive;
extern crate serde;
extern crate serde_xml_rs;
extern crate sha1;

extern crate structopt;

extern crate walkdir;
extern crate zip;

#[macro_use]
extern crate diesel;
#[macro_use]
extern crate diesel_migrations;

use compress_tools::*;
use dotenv::dotenv;
use indicatif::{ProgressBar, ProgressStyle};
use log::{debug, info, LevelFilter};
use models::{NewRomFile, RomFile};
use pretty_env_logger::env_logger::Builder;
use rayon::prelude::*;
use sha1::{Digest, Sha1};
use walkdir::{DirEntry, WalkDir};
use zip::{write::FileOptions, ZipWriter};

use std::{
    collections::HashMap,
    env,
    fs::{create_dir_all, File, OpenOptions},
    io::{BufReader, BufWriter, Read, Write},
    path::{Path, PathBuf},
};

pub mod logiqx;

mod db;
mod hashes;
pub mod models;
pub mod schema;

mod opts;
use opts::{Opt, StructOpt};

fn main() {
    dotenv().ok();
    let mut builder = Builder::from_default_env();

    builder.filter(None, LevelFilter::Info).init();
    let opt = Opt::from_args();

    create_dir_all(&opt.destination).expect("Couldn't create destination directory");

    info!("Using datafile: {}", opt.datafile);
    info!("Looking in path: {}", opt.path.to_str().unwrap());
    info!("Saving zips to path: {}", opt.destination.to_str().unwrap());

    let data_file = logiqx::load_datafile(&opt.datafile).expect("Couldn't load datafile");

    let database_url = env::var("DATABASE_URL").expect("DATABASE_URL must be set");

    let pool: db::DbPool = db::create_db_pool(&database_url);

    let file_name = Path::new(&opt.datafile)
        .file_name()
        .unwrap()
        .to_str()
        .unwrap();

    info!("Loading data file: {:?}", &file_name);
    let data_file_id = db::traverse_and_insert_data_file(&pool, data_file, file_name);

    let file_list = walk_for_files(&opt.path);

    let bar = ProgressBar::new(file_list.len() as u64);
    let bar_style = ProgressStyle::default_bar()
        .template("[{elapsed_precise}] {bar:40.cyan/blue} {pos:>7}/{len:7} {msg} {eta_precise}");
    bar.set_style(bar_style.clone());

    // this can probably be done during the walkdir
    let new_rom_files = get_all_rom_files_parallel(&file_list, &bar);

    info!(
        "rom files found (unpacked and packed both): {}",
        new_rom_files.len()
    );
    // this should happen during get_all_rom_files_parallel
    // that way, we can skip extracting archives that we've already checked
    // and not load things all over again
    db::import_rom_files(&pool, &new_rom_files);

    let games = db::load_parents(&pool, &data_file_id);
    info!(
        "Processing {} games with {} matching rom files",
        games.len(),
        games
            .iter()
            .map(|(_rom, rom_files)| { rom_files.len() as i32 })
            .sum::<i32>()
    );

    let zip_bar = ProgressBar::new(games.len() as u64);
    zip_bar.set_style(bar_style);

    // this is by far the ugliest code I've ever written in any language
    // I'm sorry
    // TODO: major refactor
    games.par_iter().for_each(|(game, romfiles_and_rom)| {
        let rom_files_for_game: Vec<HashMap<&str, &str>> = romfiles_and_rom
            .iter()
            .map(|(rom, rom_file)| {
                let mut romfile_properties = HashMap::new();
                romfile_properties.insert("archive_path", rom_file.path());
                romfile_properties.insert("destination_name", rom.name());
                romfile_properties.insert("source_name", rom_file.name());
                // I hate doing this string conversion
                romfile_properties.insert("in_archive", rom_file.in_archive_str());
                romfile_properties
            })
            .collect();

        let zip_file_path = PathBuf::new()
            .join(&opt.destination)
            .join(format!("{}.zip", game.name));
        debug!("Creating zip file: {:?}", zip_file_path.to_str().unwrap());

        let zip_file = OpenOptions::new()
            .create(true)
            .append(false)
            .write(true)
            .open(zip_file_path)
            .unwrap();
        let writer = BufWriter::new(zip_file);
        let mut zip_writer = ZipWriter::new(writer);
        let zip_options =
            FileOptions::default().compression_method(zip::CompressionMethod::Deflated);
        zip_writer.set_comment("Generated by mame_coalesce");

        // TODO: zip_writer.raw_copy_file_rename/2 to skip recompressing for zip files

        for properties in rom_files_for_game {
            let archive_path = *properties.get("archive_path").unwrap();
            let destination_name = *properties.get("destination_name").unwrap();
            let source_name = *properties.get("source_name").unwrap();
            let in_archive = *properties.get("in_archive").unwrap();

            let input_file = File::open(archive_path).unwrap();
            let input_reader = BufReader::new(input_file);

            if in_archive == "true" {
                let mut iter = ArchiveIterator::from_read(input_reader).unwrap();
                let mut current_name = String::default();
                for content in &mut iter {
                    match content {
                        ArchiveContents::StartOfEntry(name) => {
                            current_name = name.to_string();
                            if current_name == source_name {
                                debug!("Found file: {:?}", current_name);
                                zip_writer
                                    .start_file(destination_name, zip_options)
                                    .unwrap();
                            }
                        }
                        ArchiveContents::DataChunk(chunk) => {
                            if current_name == source_name {
                                zip_writer.write(&chunk).unwrap();
                            }
                        }
                        ArchiveContents::EndOfEntry => {
                            if current_name == source_name {
                                zip_writer
                                    .add_directory(&current_name, zip_options)
                                    .unwrap();
                            }
                        }
                        ArchiveContents::Err(e) => {
                            panic!("{:?}", e)
                        }
                    }
                }
            } else {
                debug!("Adding file not in archive: {:?}", source_name);
                zip_writer
                    .start_file(destination_name, zip_options)
                    .unwrap();
                // TOOD: ew
                input_reader.bytes().for_each(|b| {
                    zip_writer.write(&[b.unwrap()]).unwrap();
                });
                ()
            }
        }
        zip_writer.finish().unwrap();
        zip_bar.inc(1);
    });
}

fn get_all_rom_files_parallel(file_list: &Vec<DirEntry>, bar: &ProgressBar) -> Vec<NewRomFile> {
    file_list
        .par_iter()
        .fold(
            || Vec::<NewRomFile>::new(),
            |mut v: Vec<NewRomFile>, e: &DirEntry| {
                let path = e.path().to_path_buf();
                bar.inc(1);

                match RomFile::is_archive(e.path()) {
                    false => {
                        let r = NewRomFile::from_path(path);
                        v.push(r);
                        v
                    }
                    true => {
                        let mut internal = get_rom_files_for_archive(&path);
                        v.append(&mut internal);
                        v
                    }
                }
            },
        )
        .reduce(
            || Vec::<NewRomFile>::default(),
            |mut dest: Vec<NewRomFile>, mut source: Vec<NewRomFile>| {
                dest.append(&mut source);
                dest
            },
        )
}

fn get_rom_files_for_archive(path: &PathBuf) -> Vec<NewRomFile> {
    let f = File::open(path).unwrap();
    let buf = BufReader::new(f); // TODO: mmap?
    let mut name = String::default();
    let mut iter = ArchiveIterator::from_read(buf).unwrap();
    let mut sha1hasher = Sha1::default();

    let mut rom_files: Vec<NewRomFile> = Vec::default();

    for content in &mut iter {
        match content {
            ArchiveContents::StartOfEntry(s) => {
                name = s;
                sha1hasher.reset();
            }
            ArchiveContents::DataChunk(v) => {
                sha1hasher.update(&v);
            }
            ArchiveContents::EndOfEntry => {
                let sha1 = sha1hasher.finalize_reset().to_vec();
                let crc = Vec::default();
                let md5 = Vec::default();

                rom_files.push(NewRomFile::from_archive(path, &name, crc, sha1, md5));
            }
            ArchiveContents::Err(e) => {
                panic!("{:?}", e)
            }
        }
    }
    rom_files
}

fn walk_for_files(dir: &PathBuf) -> Vec<DirEntry> {
    WalkDir::new(dir)
        .into_iter()
        .filter_entry(|e| entry_is_relevant(e))
        .filter_map(|v| v.ok())
        .filter_map(|entry| match entry.file_type().is_file() {
            true => Some(entry),
            false => None,
        })
        .collect::<Vec<DirEntry>>()
}

fn entry_is_relevant(entry: &DirEntry) -> bool {
    entry
        .file_name()
        .to_str()
        .map(|s| entry.depth() == 0 || !s.starts_with('.'))
        .unwrap_or(false)
}
